spring:
  profiles: homolog
  datasource:
    url: jdbc:postgresql://localhost:5432/psiconnect_homolog
    driver-class-name: org.postgresql.Driver
    username: homolog_user
    password: homolog_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
